# Generated by Django 3.1.2 on 2021-09-13 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name_en', models.CharField(max_length=255)),
                ('about_en', models.TextField(blank=True, null=True)),
                ('short_description', models.TextField(blank=True, max_length=155, null=True)),
                ('content_language', models.CharField(choices=[('en', 'English'), ('ar', 'Arabic')], default='en', max_length=2)),
                ('effort', models.IntegerField(blank=True, null=True)),
                ('self_paced', models.BooleanField(default=False)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='program/images/')),
                ('square_image', models.ImageField(blank=True, null=True, upload_to='program/images/')),
                ('show_in_marketing', models.BooleanField(default=False)),
                ('start', models.DateTimeField(null=True)),
                ('end', models.DateTimeField(blank=True, null=True)),
                ('enrollment_start', models.DateTimeField(blank=True, null=True)),
                ('enrollment_end', models.DateTimeField(blank=True, null=True)),
                ('enrollment_domains', models.CharField(blank=True, max_length=255, null=True)),
                ('seats_limit', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('deprecated', models.BooleanField(default=False, max_length=255)),
                ('default_timezone', models.CharField(choices=[('Africa/Algiers', 'Algeria'), ('Asia/Amman', 'Amman/Jordan'), ('Asia/Beirut', 'Beirut/Lebanon'), ('Asia/Baghdad', 'Baghdad/Iraq'), ('Asia/Qatar', 'Bahrain and Qatar'), ('Africa/Cairo', 'Cairo/Egypt'), ('Asia/Dubai', 'Dubai/UAE'), ('Asia/Riyadh', 'Riyadh/KSA')], default='Asia/Amman', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ProgramCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(max_length=100)),
                ('name_ar', models.CharField(max_length=100)),
                ('order', models.IntegerField(default=1)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='category/images/')),
            ],
        ),
        migrations.CreateModel(
            name='ProgramMessagesLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=300)),
                ('content', models.TextField()),
                ('recipients', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='program.program')),
            ],
        ),
        migrations.AddField(
            model_name='program',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='program.programcategory'),
        ),
        migrations.AddField(
            model_name='program',
            name='instantiated_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='program.program'),
        ),
    ]
