# Generated by Django 3.2.7 on 2021-11-11 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_auto_20211111_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationactivity',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='application_activity', to='application.programapplication'),
        ),
    ]
