# Generated by Django 3.2.7 on 2021-11-22 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0005_programapplication_activities'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'ordering': ['pk']},
        ),
        migrations.AlterField(
            model_name='programapplication',
            name='state',
            field=models.CharField(blank=True, choices=[('in_progress', 'in_progress'), ('pending_review', 'pending_review'), ('accepted', 'accepted'), ('rejected', 'rejected'), ('on_hold', 'on_hold'), ('action_required', 'action_required')], max_length=255, null=True),
        ),
    ]
